# Start the testnet server with the command 'docker-compose up -d'

slp-validator-mongodb:
  image: mongo
  container_name: mongo-slp-validator
  ports:
    - "5555:27017" # <host port>:<container port>
  volumes:
    - ./database:/data/db
  command: mongod --smallfiles --logpath=/dev/null # -- quiet
  restart: always

slp-validator:
  build: ./production/
  dockerfile: Dockerfile
  container_name: slp-validator
  links:
    - slp-validator-mongodb
  ports:
    - "5001:5001"  # <host port>:<container port>
#  volumes:
#    - ./logs:/home/coinjoin/consolidating-coinjoin/logs
#    - ./keys:/home/safeuser/keys

  restart: always
